### ISSUE TITLE
View : bag

### ISSUE THREAD

**Issue by maximewel** [M4n0x/AriaHelper#8]
Create the "bag" views
* Bag principal view
* Item detailed view
* Add item view
* Loot preparation view
\
_Prepare empty connections to facilitate NFC & Wifi developpement_

**Comment by M4n0x** [comment]
ça vaudrait la peine de split cette issue, y a beaucoup d'éléments dessus, je dirais 1 issue par vue (si les vues ne sont pas fortement connectées), il faudra une vue supplémentaire pour la réception des loots quand il y a partage par wifi

**Comment by maximewel** [comment]
Assez d'accord, je décompose ça
